development:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_development
  pool: 5
  username: gilmar
  password: "050297"

test:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_test
  pool: 5
  username: gilmar
  password: "050297"